### ISSUE TITLE
Wrong include dir

### ISSUE THREAD

**Issue by jeandet** [mesonbuild/nlohmann_json#5]
https://github.com/mesonbuild/nlohmann_json/blob/39b8ffdd4b15d148f5bb35d8040379fb44e37a64/meson.build#L4

I think this should be ```include_directories('include')``` because we should be able to use it with ```#include <nlohmann/json.hpp>```

**Comment by sarum9in** [comment]
One more reason to add tests feature...

@mpoquet is the author I believe. Could you please fix if needed?
